#!/bin/bash -e

get_hicann_from_dnc() {
    hicann=$(python "-" "$1" <<EndOfPythonCode
import sys
import Coordinate
dnc = int(sys.argv[1])

def toHICANNOnWafers(hicann_on_dnc):
    return hicann_on_dnc.toHICANNOnWafer(Coordinate.DNCOnWafer(Coordinate.Enum(dnc)))

hicanns = [
    toHICANNOnWafers(hicann_on_dnc)
    for hicann_on_dnc in Coordinate.iter_all(Coordinate.HICANNOnDNC)]

hicann_c = hicanns[0]
print(hicann_c.id().value())

EndOfPythonCode
)
    echo $hicann
}

# parse input arguments and set variables
. ../parse_input.sh $@

# Script that sequentially sets and measures low and high FG settings
#  on all reticle's HICANNs, for each ADC board.
TEST_SCRIPT=sthal_hwtest_wafer_AnaRM.py
# Script that, for this test, validates the triggers for one HICANN per reticle
TRIGGER_TEST_SCRIPT=sthal_hwtest_SingleHICANN.py

# Files and folders
OUTDIR="${OUTDIR}/${TAG:-test}/data"
POSTFIX="wafer${WAFER}_dnc$(printf %02d ${DNC})"
RESULT_FOLDER="${OUTDIR}/${POSTFIX}" # Folder generated by the test script

#Obtain sthal's tests path where test script is located
pythonpaths=$(echo $PYTHONPATH | tr ":" "\n")
for testpaths in $pythonpaths
do
   if [[ $testpaths == *"/lib"* ]]; then
      testpath="${testpaths/\/lib/\/bin}"
   fi
done

if [ -z "${testpath}" ]; then
   echo "A sthal project should be present in PYTHONPATH"
   exit 7
fi

mkdir -p ${RESULT_FOLDER}

"${testpath}"/"${TEST_SCRIPT}" \
    --hwdb ${HWDB} --wafer ${WAFER} --dnc ${DNC} --data-output-dir ${OUTDIR}

if ! [[ $SKIP_TRIGGER_TEST ]]; then
    HICANN=$(get_hicann_from_dnc $DNC)
    echo "HICANN used for trigger tests: " ${HICANN}

    HICANN_VERSION=$(query_hwdb hicann-version --hicann "${HICANN}" --wafer "${WAFER}")
    echo "HICANN version: "  ${HICANN_VERSION}
    "${testpath}"/"${TRIGGER_TEST_SCRIPT}" \
     --wafer ${WAFER} --hicann ${HICANN} --skip-non-trigger --v${HICANN_VERSION} --xml-output-dir ${RESULT_FOLDER}
fi
